In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from karateclub.node_embedding.neighbourhood.deepwalk import DeepWalk
import matplotlib
matplotlib.use('TkAgg')
print(matplotlib.__version__)


3.7.1


In [2]:
#Erstellen eines zufälligen Spannbaums aus einem vollständigen Graphen mit 40 Knoten
G = nx.random_spanning_tree(nx.complete_graph(40)) 

print(type(G))
print(G.nodes) # Liste alle Knoten im Graphen auf
print(G.edges) # Liste alle Kanten im Graphen auf

<class 'networkx.classes.graph.Graph'>
[3, 7, 15, 39, 13, 26, 36, 31, 32, 38, 0, 2, 1, 6, 5, 28, 27, 19, 30, 37, 10, 33, 23, 4, 35, 11, 25, 12, 16, 24, 34, 21, 14, 29, 17, 20, 8, 22, 18, 9]
[(3, 7), (3, 17), (3, 20), (7, 38), (7, 12), (15, 39), (15, 36), (39, 13), (13, 4), (26, 36), (36, 19), (36, 29), (31, 32), (31, 5), (31, 27), (31, 24), (0, 2), (2, 21), (1, 6), (6, 23), (5, 28), (5, 4), (5, 14), (28, 35), (28, 11), (28, 17), (27, 37), (19, 30), (30, 23), (30, 16), (10, 33), (33, 16), (33, 22), (33, 9), (35, 21), (11, 25), (11, 18), (16, 8), (24, 34)]


In [3]:
plt.figure(figsize=(8, 6)) # Erstellen einer neuer Figure

# Zeichne den Graphen G:
# - `with_labels=True`: Zeigt die Knotennummern an
# - `node_color="lightblue"`: Färbt die Knoten hellblau
# - `edge_color="gray"`: Färbt die Kanten grau
# - `node_size=500`: Setzt die Knotengröße auf 500
# - `font_size=10`: Legt die Schriftgröße für die Labels fest
nx.draw(G, with_labels=True, node_color="lightblue", edge_color="gray", node_size=500, font_size=10)
plt.show()

DeepWalk ist ein Graph Embedding Algorithmus, der Graphen in dichte Vektoren umwandelt.

In [4]:
#DeepWalk-Modell für Node-Embeddings:
deepwalk = DeepWalk(dimensions=2)

In [5]:
#Trainieren des Modells:
deepwalk.fit(G)

In [6]:
# Erhalten der berechneten Node-Embeddings nach dem Training mit DeepWalk
embedding = deepwalk.get_embedding() # 2D Visualisierung
print(embedding) #als NumPy-Array

[[-1.670454    4.2673745 ]
 [ 4.5279107   0.1828275 ]
 [-2.0431757   4.4998507 ]
 [ 1.1123059   1.5499386 ]
 [ 0.2389931   1.1946176 ]
 [-0.530614    1.7620527 ]
 [ 4.8672433   0.0448513 ]
 [ 1.7208456   1.34149   ]
 [ 3.4723012   0.18454985]
 [ 2.6717994   0.40956196]
 [ 3.959263    0.44169992]
 [-0.9165274   3.0089679 ]
 [ 2.381122    1.8716158 ]
 [ 0.7847552   1.0408247 ]
 [-0.5559252   1.7811813 ]
 [ 1.4506755   0.79162496]
 [ 3.2302194   0.47663665]
 [ 0.9091871   1.4753836 ]
 [-0.8179997   2.900734  ]
 [ 3.201664    0.4221499 ]
 [ 1.6900012   1.9805211 ]
 [-1.8445165   3.9933197 ]
 [ 3.3513956   0.4790041 ]
 [ 4.108259    0.228913  ]
 [-1.6312338   3.339303  ]
 [-0.90053916  2.9146    ]
 [ 2.9755      0.635878  ]
 [-1.643971    3.0925565 ]
 [-0.3503328   1.9861932 ]
 [ 3.0703375   0.82206506]
 [ 3.2970335   0.14522839]
 [-1.3723491   2.9481862 ]
 [-1.5102745   2.6579096 ]
 [ 4.455745    0.66681075]
 [-1.7309973   2.9414399 ]
 [-1.302889    2.9729521 ]
 [ 2.5956802   0.46425518]
 

In [7]:
plt.scatter(embedding[:,0], embedding[:, 1])
plt.show()

In [8]:
#Erstellemn 3D-Models:
deepwalk = DeepWalk(dimensions=3) 

In [9]:
#Trainieren des Modells:
deepwalk.fit(G)

In [10]:
embedding = deepwalk.get_embedding()
print(embedding)# 3D Visualisierung

[[-6.4312620e-04  1.0494937e+00 -4.8073354e+00]
 [ 3.8129492e+00  3.4330659e+00  1.6716833e+00]
 [-7.2665244e-02  1.1504256e+00 -4.5838647e+00]
 [-2.8035769e+00  2.9549236e+00 -1.8008105e-01]
 [ 2.1709440e+00  5.5876553e-01 -1.6805185e+00]
 [ 7.0739198e-01  3.1179091e-01 -1.4695472e+00]
 [ 3.8088439e+00  4.0597129e+00  1.9828235e+00]
 [-2.5982132e+00  3.3089228e+00  5.1469052e-01]
 [-4.0141967e-01  3.4536476e+00  2.1943421e+00]
 [-8.4244519e-01  3.2841871e+00  1.8010849e+00]
 [-6.4013499e-01  3.3398931e+00  2.0290809e+00]
 [-2.6693861e+00  1.5685858e+00 -2.5868311e+00]
 [-2.6884441e+00  3.0983427e+00 -3.6970921e-02]
 [ 3.6490238e+00  6.6999227e-01 -2.3744657e+00]
 [ 4.9378142e-01  6.2099195e-01 -1.3234978e+00]
 [ 3.2217910e+00  1.1685401e+00 -1.0071255e+00]
 [-1.0113096e-01  3.2158852e+00  1.7305396e+00]
 [-2.0199583e+00  1.9692750e+00 -2.5176549e-01]
 [-2.5320890e+00  1.3961478e+00 -3.1215079e+00]
 [ 2.6573212e+00  2.3131402e+00  1.0762386e+00]
 [-3.1149187e+00  3.3987761e+00  5.11583

In [11]:
# Erstelle einer neuen 3D-Figure
fig=plt.figure(figsize=(15,8))
#3D-Plot-Subplot:
ax= fig.add_subplot(projection="3d")
# Scatter-Plot der Embeddings:
# - `embedding[:,0]`: Erste Dimension
# - `embedding[:,1]`: Zweite Dimension
# - `embedding[:,2]`: Dritte Dimension
ax.scatter(embedding[:,0], embedding[:,1], embedding[:,2])
plt.show()

Alternativen:

In [12]:
from karateclub.node_embedding.neighbourhood import DeepWalk
from sklearn.decomposition import PCA

# DeepWalk auf dem Graphen anwenden
model = DeepWalk(dimensions=2)  # 2D-Embedding für Visualisierung
model.fit(G)
embeddings = model.get_embedding()

# Reduktion auf 2D mit PCA (falls nötig)
pca = PCA(n_components=2)
reduced_embeddings = pca.fit_transform(embeddings)

# Scatter-Plot der Knoten basierend auf Embeddings
plt.figure(figsize=(8, 6))
plt.scatter(reduced_embeddings[:, 0], reduced_embeddings[:, 1], c="lightblue", edgecolors="black")

# Knotenbeschriftungen
for i, (x, y) in enumerate(reduced_embeddings):
    plt.text(x, y, str(i), fontsize=10, ha='right')

plt.xlabel("Dimension 1")
plt.ylabel("Dimension 2")
plt.title("Graph-Node Embeddings mit DeepWalk")
plt.show()

In [13]:

plt.figure()
pos = nx.spring_layout(G)  # Manuelle Layout-Berechnung
nx.draw(G, pos, with_labels=True, node_color="lightblue", edge_color="gray")
plt.show()

In [14]:
plt.figure()
nx.draw(G, with_labels=True)
plt.show()